### ISSUE TITLE
Add state for cancelled or failed deploys

### ISSUE THREAD

**Issue by dChiamp** [funkhaus/netlify-deploy#1]
It appears that the deploy button disappears when netlify builds are cancelled or failed:
<img width="568" alt="Screen Shot 2022-10-21 at 11 43 56 AM" src="https://user-images.githubusercontent.com/13562688/197267593-74e33e20-d52c-4779-8658-9b1c4160370e.png">

**Comment by drewbaker** [comment]
This was fixed 5 days ago: https://github.com/funkhaus/netlify-deploy/commit/6eb19c2164551358b7984e333aee112b6396dce4

Can you update your plugin and if it's still broken I will re-open
